version: '3.9'
services:
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.21
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      interval: 5s
      timeout: 10s
      retries: 10
